services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 30

  prestashop:
    image: prestashop/prestashop:9
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}

      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO}
      PS_DEV_MODE: ${PS_DEV_MODE}
      PS_DOMAIN: ${PS_DOMAIN}

      ADMIN_MAIL: ${ADMIN_MAIL}
      ADMIN_PASSWD: ${ADMIN_PASSWD}
      PS_LANGUAGE: ${PS_LANGUAGE}
      PS_COUNTRY: ${PS_COUNTRY}
    volumes:
      - ps_data:/var/www/html
      - ./modules/b2block:/var/www/html/modules/b2block

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "${MAILPIT_UI_PORT}:8025"   # Web UI
      - "${MAILPIT_SMTP_PORT}:1025" # SMTP

volumes:
  db_data:
  ps_data:
