name: jc_rouquier
display_name: JC Rouquier
version: 1.0.0
author:
  name: Nicolas Metivier

meta:
  compatibility:
    from: 9.0.0
    to: ~
  available_layouts:
    layout-full-width:
      name: Full width layout
      description: Ideal for product pages to maximize picture size

parent: classic

assets:
  use_parent_assets: true

  css:
    all:
      - id: google-font-inter
        path: https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800&display=swap
        priority: 50
      - id: jc-rouquier-main-css
        path: assets/css/main.css
        priority: 200

  js:
    all:
      - id: jc-rouquier-main-js
        path: assets/js/main.js
        priority: 200
